branches:
  only:
  - master
image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - ps: dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  publish_nuget: true
  verbosity: minimal

after_build:
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
- provider: NuGet
  api_key:
    secure: tB07PzZh5PA2UE5HOXhbEkVopmU4fOOwsIEeAAJPnSr/bE7a9k2LAC7WP/Ac6pWq
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: rZCSsjj4ffS5ik+l6+LfiCPTCYkkrxqdd/icVhGn7Qclw+xu2v8xnltbuDBnloj30uoYBd+NKnGXHSJszC6RSQwFkTkG2JIyPjUSfCG3ZFk=
  on:
    branch: master